### ISSUE TITLE
Allow multiple configurations of the same provider

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot-app-secrets-providers#67]
### Environment
* Nautobot version:  1.5.8
* secrets version:  1.3.0

### Proposed Functionality

Allow multiple configurations for the same secrets provider.

### Use Case

In our environment we have multiple hashicorp vault deployments, one for our department and one corporate/enterprise one.  I would like to be able to get secrets from both vault deployments.

**Comment by HanlinMiao** [comment]
Notes from Design review:

1. Revamp the app to be able to configure multiple instances of the same secrets provider
2. We need to reconfigure plugin_settings = settings.PLUGINS_CONFIG["nautobot_secrets_providers"]["hashicorp_vault"] to a list of dictionaries or multiple keys (hashicorp_vault_1, and hashicorp_vault_2 etc.)
3. Since `HashiCorpVaultSecretsProvider` only contains class methods we might need to think of the possibility of dynamically declaring similar classes as `HashiCorpVaultSecretsProvider1` or `HashiCorpVaultSecretsProvider2` and, etc.
4. Consider the possibility of implementing `name` and `slug` attributes as @property classes so that each dynamically generated classes can automatically override those property classes in order to distinguish themselves.
5. Core does enforce that providers be subclass objects not instances maybe we can change this.
6. We can add an additional field (perhaps optional) to the ParametersForm in the provider class definition in order to specify one of several config sets (probably the easiest one to implement, could also make an effort to make this backward-compatible).

**Comment by lampwins** [comment]
Please prioritize this not being a breaking change.

**Comment by lampwins** [comment]
The scope of this issue will be to implement his pattern for only the HashiCorp Vault provider.

**Comment by bintangf** [comment]
any plan to backport to 1.6.x LTM version?
